name: EejitsTools
version: '${project.version}'
main: com.eejitstools.eejitstools.EejitsTools
api-version: 1.19
authors: [ Eejit ]
description: A simple plugin for personal use
commands:
  setid:
    description: Set an item's "id" tag to the given value
    usage: /<command> <id>
  reloadconfig:
    description: Reload the config file
    usage: /<command>